# -*- coding: utf-8 -*-
"""Aula  IA 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19c1i_jhOGtYDOG_MfOhBagXyubBpBf5K

##AULA 01 INTELIGENCIA ARTIFICIAL###
### LEITURA DE ARQUIVOS E VALOR MEDIO####
"""

import pandas as pd

dados = pd.read_excel("/content/dados.xltx")
dados

soma=0
for i in range(3):
  soma+=dados.valorVendas[i]

print(soma/len(dados.valorVendas))

dados.valorVendas.sum()

dados.valorVendas.mean()

dados.valorVendas.median()

for nm,sb in zip(dados.nome,dados.salarioBase):
  if sb<2000:
    print(nm)